export const ACCEES_TOKEN = "acceesToken";

export const CustomError = {
  ACCESS_TOKEN_EXPIRED: "AUTH_ERROR1",
  SESSION_EXPIRED: "AUTH_ERROR2",
  PASSWORD_ERROR: "AUTH_ERROR3",
  NO_DATA: "SVC_ERROR1",
  EMAIL_ALREADY_REGISTERED: "SVC_ERROR2",
  EMAIL_NOT_FOUND: "SVC_ERROR3",
  EMAIL_SEND_FAILED: "SVC_ERROR4",
  INVALID_VERIFICATION_CODE: "SVC_ERROR5",
};
